language: python
python:
  - 2.7
  - 3.6

env:
  - ODOOVERSION=9.0 LINT=false
  - ODOOVERSION=10.0 LINT=false
  - ODOOVERSION=11.0 LINT=false

matrix:
  exclude:
  - python: 3.6
    env: ODOOVERSION=9.0 LINT=false
  - python: 3.6
    env: ODOOVERSION=10.0 LINT=false
  - python: 2.7
    env: ODOOVERSION=11.0 LINT=false
  include:
  - python: 3.6
    env: LINT=true

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - python-lxml # because pip installation is slow

before_script:
  - if [ "$LINT" == false ] ; then pip install invoke pytest ; fi
  - if [ "$LINT" == false ] ; then pip install . ; fi
  - if [ "$LINT" == false ] ; then invoke tests.prepare-version "${ODOOVERSION}" ; fi
  - if [ "$LINT" == true ] ; then pip install flake8 readme_renderer ; fi

script:
  - if [ "$LINT" == false ] ; then OPENERP_SERVER=/tmp/test-anthem-config-${ODOOVERSION}.cfg py.test tests ; fi
  - if [ "$LINT" == true ] ; then flake8 anthem tests ; fi
  - if [ "$LINT" == true ] ; then python setup.py check -r -s ; fi

deploy:
  provider: pypi
  skip_existing: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/anthem
    branch: master
    tags: true
